### ISSUE TITLE
Enums and EOFs

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/libs#1]
https://github.com/marekmaskarinec/libs/blob/99e7083d7af4eae5762b7985aac3880f8852cb32/json.um#L30

As you know, Go doesn't have `enum`s. Do you mean C++-style `class enum`s? Or just an automatic assignment of successive integers to `const`s, like with Go's `iota`?

https://github.com/marekmaskarinec/libs/blob/243b51126ec7a7d90dda9f6a9a7e5fed9572defc/json.um#L58

The EOF is generally not a character. That's why `fgetc()` in C returns an `int` rather than a `char`. Do you mean a similar approach?

**Comment by marekmaskarinec** [comment]
> As you know, Go doesn't have enum s. Do you mean C++-style class enum s? Or just an automatic assignment of successive integers to const s, like with Go's iota ?

Just automatic assigning of constants. I'm not sure, how that would look. Would you allow constant definitons without a value and then assign one?

> The EOF is generally not a character. That's why fgetc() in C returns an int rather than a char . Do you mean a similar approach

In this case using \0 is better, but I think std.um could have an EOF constant. I think eof is defined as -1 in glibc, but it could be different based on the implementation. This could be easily avoided by making is a function.

**Comment by vtereshkov** [comment]
Enums implemented.

**Comment by marekmaskarinec** [comment]
Cool. I think we can close this, since the enums were the most important. As for EOF, I could make a pr with functions in `std.um`, that returns values of constants like EOF, or stderr.
